FROM php:7-apache
LABEL authors="Nicolas Borboën <nicolas.borboen@epfl.ch>"
WORKDIR /
RUN apt update
RUN curl -o tequila-php-client.tgz https://tequila.epfl.ch/download/2.0/tequila-php-client-3.0.3.tgz
RUN tar zxvf tequila-php-client.tgz
WORKDIR /build/tequila-3.0.3/clients/php/
RUN mkdir -p /var/www/Tequila/clients/php/3.0.3/
RUN cp -r /build/tequila-3.0.3/clients/php/* /var/www/Tequila/clients/php/3.0.3/
RUN rm -rf /build
WORKDIR /var/www/html
